// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Show")]
	public class Show
	{
		[Column("ShowNr"        , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long   ShowNr         { get; set; } // integer
		[Column("Name"          , CanBeNull    = false                                                             )] public string Name           { get; set; } = null!; // text(max)
		[Column("Description"   , CanBeNull    = false                                                             )] public string Description    { get; set; } = null!; // text(max)
		[Column("ReleaseDate"   , CanBeNull    = false                                                             )] public string ReleaseDate    { get; set; } = null!; // text(max)
		[Column("IsReleasing"                                                                                      )] public long   IsReleasing    { get; set; } // integer
		[Column("Image"         , CanBeNull    = false                                                             )] public byte[] Image          { get; set; } = null!; // blob
		[Column("AlreadyWatched"                                                                                   )] public long   AlreadyWatched { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_WatchlistShow_1_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(ShowNr), OtherKey = nameof(WatchlistShow.ShowNr))]
		public IEnumerable<WatchlistShow> WatchlistShows { get; set; } = null!;
		#endregion
	}
}
