// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("ShowTag")]
	public class ShowTag
	{
		[Column("ShowNr"                                                                                     )] public long ShowNr    { get; set; } // integer
		[Column("TagNr"                                                                                      )] public long TagNr     { get; set; } // integer
		[Column("ShowTagNr", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long ShowTagNr { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_ShowTag_0_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(TagNr), OtherKey = nameof(Tag.TagNr))]
		public Tag FkShowTag00 { get; set; } = null!;

		/// <summary>
		/// FK_ShowTag_1_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(ShowNr), OtherKey = nameof(Show.ShowNr))]
		public Show FkShowTag10 { get; set; } = null!;
		#endregion
	}
}
