// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Tag")]
	public class Tag
	{
		[Column("TagNr", IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long   TagNr { get; set; } // integer
		[Column("Name" , CanBeNull    = false                                                             )] public string Name  { get; set; } = null!; // text(max)

		#region Associations
		/// <summary>
		/// FK_ShowTag_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(TagNr), OtherKey = nameof(ShowTag.TagNr))]
		public IEnumerable<ShowTag> ShowTags { get; set; } = null!;
		#endregion
	}
}
