// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("WatchlistShow")]
	public class WatchlistShow
	{
		[Column("WlNr"  , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public long WlNr   { get; set; } // integer
		[Column("ShowNr", IsPrimaryKey = true, PrimaryKeyOrder = 1)] public long ShowNr { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_WatchlistShow_0_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(WlNr), OtherKey = nameof(Watchlist.WlNr))]
		public Watchlist FkWatchlistShow00 { get; set; } = null!;

		/// <summary>
		/// FK_WatchlistShow_1_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(ShowNr), OtherKey = nameof(Show.ShowNr))]
		public Show FkWatchlistShow10 { get; set; } = null!;
		#endregion
	}
}
