// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Watchlist")]
	public class Watchlist
	{
		[Column("WlNr", IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long   WlNr { get; set; } // integer
		[Column("Name", CanBeNull    = false                                                             )] public string Name { get; set; } = null!; // text(max)

		#region Associations
		/// <summary>
		/// FK_WatchlistShow_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(WlNr), OtherKey = nameof(WatchlistShow.WlNr))]
		public IEnumerable<WatchlistShow> WatchlistShows { get; set; } = null!;
		#endregion
	}
}
